version: '3'
services:
  app:
    image: efalrk/rekber-backend:latest #Jika build sendiri jadikan image menjadi nama build image mu
    container_name: golang-app
    ports:
      - "9090:9090"
    env_file:
      - docker.env #Template .env ada di .env.example
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27015:27017" #port di sesuaikan di env file mu
