version: '3'
services:
  app:
    image: efalrk/rekber-backend:latest #jika tidak dari hub maka hapus efalrk/ jadi hanya rekber-backend:latest
    container_name: golang-app
    ports:
      - "9090:9090"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27015:27017" #port di sesuaikan di env file mu
